#!/bin/csh

#$ -M jliu16@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -q gpu
#$ -pe mpi-16 16	 # Specify parallel environment and legal core size
#$ -q long		 # Specify queue
#$ -N cifar10_evaluation_c2   # Specify job name

module load cuda/8.0     # Required modules
module load tensorflow/0.12-python2	         # Required modules

python cifar10_train.py > evaluation_c2_record # Application to execute
