#!/bin/csh

#$ -M jliu16@nd.edu	 # Email address for job notification
#$ -m abe		 # Send mail when job begins, ends and aborts
#$ -pe smp 4		 # Specify parallel environment and legal core size
#$ -q gpu		 # Specify queue
#$ -N c10_e_c2_cpu   # Specify job name

module load cuda/8.0     # Required modules
module load tensorflow/0.12-python2	         # Required modules

python cifar10_eval.py > evaluation_c2_record # Application to execute
